- all_version: 0
  app_store: 0
  arm: 1
  name: Macs Fan Control
  path: ''
  remark: ''
  show_name: ''
  version: 1.5.16
  x86: 0
- all_version: 1
  app_store: 0
  arm: 1
  name: Things3
  path: ''
  remark: ''
  show_name: ''
  version: 3.19.6
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: Xnip
  path: ''
  remark: ''
  show_name: ''
  version: 2.2.3
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: Transmit
  path: ''
  remark: ''
  show_name: ''
  version: 5.10.4
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: BuhoCleaner
  path: ''
  remark: ''
  show_name: ''
  version: 1.10.4
  x86: 1
- all_version: 0
  app_store: 1
  arm: 1
  name: Image2Icon
  path: ''
  remark: ''
  show_name: ''
  version: '2.18'
  x86: 0
- all_version: 0
  app_store: 1
  arm: 1
  name: FileZilla Pro
  path: ''
  remark: ''
  show_name: ''
  version: 3.66.5
  x86: 0
- all_version: 1
  app_store: 1
  arm: 1
  name: menubarx
  path: ''
  remark: ''
  show_name: ''
  version: ''
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: SQLPro Studio
  path: ''
  remark: ''
  show_name: ''
  version: '2023.35'
  x86: 1
- all_version: 0
  app_store: 0
  arm: 1
  name: Texifier
  path: ''
  remark: ''
  show_name: ''
  version: 1.9.27
  x86: 0
- all_version: 1
  app_store: 1
  arm: 1
  name: Sketch
  path: ''
  remark: ''
  show_name: ''
  version: '100'
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: OmniRecorder
  path: ''
  remark: ''
  show_name: Omi录屏专家
  version: 1.3.8
  x86: 1
- all_version: 0
  app_store: 0
  arm: 1
  name: CleanShot X
  path: ''
  remark: ''
  show_name: ''
  version: '4.7'
  x86: 0
- all_version: 0
  app_store: 0
  arm: 1
  name: Aldente Pro
  path: ''
  remark: 暂停支持
  show_name: ''
  version: 1.26.1
  x86: 0
- all_version: 0
  app_store: 0
  arm: 1
  name: Table Plus
  path: ''
  remark: 暂停支持
  show_name: ''
  version: 6.0.4
  x86: 0
- all_version: 1
  app_store: 0
  arm: 1
  name: Doppler
  path: ''
  remark: ''
  show_name: ''
  version: 2.1.21
  x86: 1
- all_version: 0
  app_store: 1
  arm: 1
  name: Text Scanner
  path: ''
  remark: 终端执行其二进制文件
  show_name: ''
  version: 1.7.5
  x86: 0
- all_version: 1
  app_store: 0
  arm: 1
  name: Eudic
  path: ''
  remark: ''
  show_name: 欧陆词典
  version: 4.6.6
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Blocs
  path: ''
  remark: ''
  show_name: ''
  version: ''
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: PlistEdit Pro
  path: ''
  remark: ''
  show_name: ''
  version: 1.9.7
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Downie 4
  path: ''
  remark: ''
  show_name: ''
  version: 4.7.2
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Typora
  path: ''
  remark: ''
  show_name: ''
  version: 1.8.10
  x86: 1
- all_version: 0
  app_store: 0
  arm: 1
  name: Stash
  path: ''
  remark: ''
  show_name: ''
  version: 2.6.2
  x86: 0
- all_version: 0
  app_store: 0
  arm: 1
  name: App Cleaner
  path: ''
  remark: ''
  show_name: ''
  version: 8.3.1
  x86: 0
- all_version: 1
  app_store: 1
  arm: 1
  name: Hype4
  path: ''
  remark: ''
  show_name: ''
  version: 4.1.18
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: Infuse
  path: ''
  remark: ''
  show_name: ''
  version: 7.8.4860
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Kaleidoscope
  path: ''
  remark: ''
  show_name: ''
  version: 4.5.1
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Pixelmator Pro Trial
  path: ''
  remark: ''
  show_name: ''
  version: 3.5.9
  x86: 1
- all_version: 0
  app_store: 0
  arm: 1
  name: Proxyman
  path: ''
  remark: ''
  show_name: ''
  version: 5.2.0
  x86: 0
- all_version: 0
  app_store: 1
  arm: 1
  name: ServerCat
  path: ''
  remark: ''
  show_name: ''
  version: '1.12'
  x86: 0
- all_version: 1
  app_store: 1
  arm: 1
  name: Core Tunnel
  path: ''
  remark: ''
  show_name: ''
  version: 3.8.6
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: Navicat Premium
  path: ''
  remark: 借鉴 Qiuchenly
  show_name: ''
  version: 17.0.6
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Permute 3
  path: ''
  remark: ''
  show_name: ''
  version: 3.11.10
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Eon
  path: ''
  remark: ''
  show_name: ''
  version: 2.9.12
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: UctoX 2
  path: ''
  remark: ''
  show_name: ''
  version: 2.9.14
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Rottenwood
  path: ''
  remark: ''
  show_name: ''
  version: '1.3'
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: Judo
  path: ''
  remark: 免登录 有几个功能不能用
  show_name: ''
  version: 7.0.4
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: Querious
  path: ''
  remark: ''
  show_name: ''
  version: 4.0.13
  x86: 1
- all_version: 1
  app_store: 0
  arm: 1
  name: ForkLift
  path: ''
  remark: ''
  show_name: ''
  version: 4.1.5
  x86: 1
- all_version: 1
  app_store: 1
  arm: 1
  name: CleanMyMac-MAS
  path: ''
  remark: 不包括状态栏按钮
  show_name: ''
  version: 4.15.4
  x86: 1
- all_version: 0
  app_store: 0
  arm: 1
  name: Reveal
  path: ''
  remark: ''
  show_name: ''
  version: 49 (20463)
  x86: 0
- all_version: 1
  app_store: 0
  arm: 1
  name: HoudahSpot
  path: ''
  remark: ''
  show_name: ''
  version: 6.5.4
  x86: 1
